server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/gyh/Documents/Workspace/cloud/git-local-repo
        #          username: <github-id>
        #          password: <gihub-accessToken>
        bootstrap: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 5
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh