spring:
  datasource:
    url: jdbc:mariadb://localhost:2306/MSA
    username: msa
    password: "{cipher}5d0323a2de277824abb1d97226e8839d330ee98ff5404313722cf45cae29fb7b"

token:
  expiration_time: 86400000
  secret: user_my_token_user_my_token_user_my_token_user_my_token_user_my_token_22
gateway:
  ip: 192.168.0.1
