spring:
  datasource:
    url: jdbc:mariadb://localhost:2306/MSA
    username: msa
    password: "{cipher}64b32bd025b25417f17c39defe48585a60601b2f8752bb149acc2101d9c46647"

token:
  expiration_time: 86400000
  secret: user_my_token_user_my_token_user_my_token_user_my_token_user_my_token

gateway:
  ip: 192.168.0.1

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
